name: ocli-hubspot
base: core22
version: git
summary: Command-line interface for HubSpot
description: |
  hspt is a CLI for managing HubSpot CRM.

  Features:
  - Manage contacts, companies, and deals
  - Query and update CRM records
  - Table, JSON, and plain output formats

  Run 'hspt init' to configure your HubSpot credentials.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

plugs:
  dot-config-hubspot-cli:
    interface: personal-files
    read:
      - $HOME/.config/hubspot-cli
    write:
      - $HOME/.config/hubspot-cli

apps:
  ocli-hubspot:
    command: bin/hspt
    plugs:
      - home
      - network
      - dot-config-hubspot-cli
    aliases:
      - hspt

parts:
  hspt:
    plugin: go
    source: .
    build-snaps:
      - go/1.24/stable
    build-environment:
      - CGO_ENABLED: "0"
    override-build: |
      # Get version from git
      VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
      COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
      DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

      # Build with ldflags
      go build -o $SNAPCRAFT_PART_INSTALL/bin/hspt \
        -ldflags "-s -w \
          -X github.com/open-cli-collective/hubspot-cli/internal/version.Version=${VERSION} \
          -X github.com/open-cli-collective/hubspot-cli/internal/version.Commit=${COMMIT} \
          -X github.com/open-cli-collective/hubspot-cli/internal/version.BuildDate=${DATE}" \
        ./cmd/hspt
